### ISSUE TITLE
docs: 开源了能不能给点mock数据 让我们登陆的时候方便些

### ISSUE THREAD

**Issue by william-xue** [FEMessage/create-nuxt-app#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lianghx-319** [comment]
是 admin 的登录帐号吗？
admin/admin/abcd1234

- 后续把环境变量注明在文档中，即可方便直接运行了。
- 暂时只有登录和菜单的 mock 数据
