### ISSUE TITLE
It seems like not used

### ISSUE THREAD

**Issue by shoyuf** [FEMessage/create-nuxt-app#117]
https://github.com/FEMessage/create-nuxt-app/blob/1289ad87aa8c644d052948b721afe46b669fbea8/template/framework-mobile/_package.json#L58

它好像没有在eslint中使用 `eslint --format`

And: **eslint-friendly-formatter is moved to eslint-formatter-friendly**

**Comment by lianghx-319** [comment]
移动端可能因为使用得比较少，有些依赖可能确实没有及时更新。welcome to PRs
