### ISSUE TITLE
为什么我这会有警告

### ISSUE THREAD

**Issue by Xin-X** [FEMessage/create-nuxt-app#3]
WARN  BrowserslistError: Unknown browser query android all

**Comment by lianghx-319** [comment]
有具体的重现步骤吗？

**Comment by Xin-X** [comment]
在启动项目的时候

i Preparing project for development                                                                                                                                                                           10:41:52
i Initial build may take a while                                                                                                                                                                              10:41:52
√ Builder initialized                                                                                                                                                                                         10:41:52
√ Nuxt files generated                                                                                                                                                                                        10:41:52

 WARN  BrowserslistError: Unknown browser query android all                                                                                                                                                   10:41:54


 WARN  BrowserslistError: Unknown browser query android all                                                                                                                                                   10:41:54


 WARN  BrowserslistError: Unknown browser query android all                                                                                                                                                   10:41:54


 WARN  BrowserslistError: Unknown browser query android all       

 WARN  BrowserslistError: Unknown browser query android all                                                                                                                                                   10:41:55


 WARN  BrowserslistError: Unknown browser query android all                                                                                                                                                   10:41:55


√ Client
  Compiled successfully in 5.29s

i Waiting for file changes                                                                                                                                                                                    10:42:01
i Memory usage: 167 MB (RSS: 233 MB)

**Comment by lianghx-319** [comment]
请提供一下你当前的 nuxt 版本和 caniuse-lite 的版本，nuxt 默认 lock 在 2.7.1。

- 请确保使用 yarn 安装依赖，因为有些依赖版本需要 lock
- 安装后检查 nuxt 版本是否在 2.7.1

**Comment by william-xue** [comment]
有你们的项目在 我感觉根本不需要自己搭建脚手架了 学习复用你们的就行了
